import { getStore } from "@netlify/blobs";

// Amorçage unique : si le registre est vide, on y insère les dossiers déjà
// constitués pendant le roleplay. Appeler /api/seed une seule fois après le
// déploiement (puis cette fonction ne réécrit rien si des données existent).

const store = () => getStore({ name: "dossiers-medicaux", consistency: "strong" });
const KEY = "index";

const SEED = [
  {id:"001",ref:"REF/MED/2026-0512-Z",name:"Zerath Cobalt",date:"12 / 05 / 2026",unit:"Admission · Soins intensifs",status:"traite",category:"Soins intensifs",tags:["Brûlure","Chirurgie oculaire","Antécédent DPPA"],summary:"Brûlure au flanc droit et retrait d'un œil nécrosé. Implant orbitaire provisoire posé.",body:"ANTÉCÉDENTS & ÉTAT À L'ADMISSION\n— Soins préalables prodigués par un médecin de la DPPA en amont de l'admission.\n— Brûlure au niveau du flanc droit — prise en charge partiellement amorcée.\n\nINTERVENTIONS RÉALISÉES\n— Opération oculaire : retrait d'un œil nécrosé dans l'orbite droite.\n— Globe oculaire extrait — mise en place d'un implant orbitaire provisoire dans l'attente d'une prothèse oculaire définitive.\n\nTRAITEMENT MÉDICAMENTEUX\n— Antalgiques — gestion des douleurs liées aux brûlures.\n— Antibiotiques — prévention des infections post-opératoires.\n— Traitement protecteur de l'œil sain — prévention des complications sympathiques."},
  {id:"002",ref:"REF/MED/2026-0512-F",name:"Diane Flori",date:"12 / 05 / 2026 → 13 / 05 / 2026",unit:"Admission · Urgences chirurgicales",status:"traite",category:"Neurochirurgie",tags:["Polytraumatisée","Brûlure","Éclats de grenade","Neurochirurgie"],summary:"Polytraumatisme par explosion. Neurochirurgie crânienne, drainage thoracique, fêlure pelvienne. Réveil confirmé.",body:"⚠ ERREUR MÉDICALE SIGNALÉE\nPerfusion de sang AB+ administrée par le Dr. Leon Katchum à une patiente O+ — incompatibilité ABO. Insuffisance rénale aiguë. Correction immédiate, traitement engagé.\n\nMEMBRES SUPÉRIEURS — Brûlures et éclats de grenade aux deux bras. Extraction, tulle gras + bandage.\nMEMBRE INFÉRIEUR — Brûlures à la jambe, tulle gras + bandage.\nNEUROCHIRURGIE — Fracture crânienne, plaque métallique, fermeture du scalp par agrafes.\nTHORAX — Débris métalliques retirés, valve de drainage au 2e espace intercostal.\nBASSIN — Fêlure pelvienne, antalgie renforcée, fauteuil roulant.\n\nTRAITEMENT — Mannitol, Antibiotiques, Morphine, Kétamine.\n✓ Réveil confirmé le 13/05/2026 à 22H16."},
  {id:"003",ref:"REF/MED/2026-0515-T",name:"Tadao",date:"15 / 05 / 2026",unit:"Admission · Soins chirurgicaux",status:"traite",category:"Chirurgie",tags:["Infection","Amputation","Désarticulation épaule"],summary:"Infection du moignon après désarticulation d'épaule. Débridement chirurgical et antibiothérapie.",body:"⚠ INFECTION POST-AMPUTATION\nFoyer infectieux actif sur le moignon de désarticulation d'épaule.\n\nADMISSION — Amputation récente à l'épaule droite. Démangeaisons intenses. Suintement purulent, rougeur, chaleur.\nINTERVENTIONS — Ablation des sutures infectées, lavage sous pression, débridement chirurgical, prélèvements bactériologiques, pansement hydrofibres, cataplasme Baie Oran, Comfey au contact.\nTRAITEMENT — Antibiotiques IV (Amoxicilline-Ac. Clavulanique), anti-inflammatoires locaux."},
  {id:"004",ref:"REF/MED/2026-0515-AD",name:"Alex Delacroix",date:"15 / 05 / 2026",unit:"Consultation externe",status:"traite",category:"Toxicologie",tags:["Intoxication","Spores Raphlesia","Perte de connaissance"],summary:"Certificat attestant une intoxication involontaire par spores de Raphlesia. Aucun traitement administré.",body:"ATTESTATION — Intoxication par spores de Raphlesia subie sans consentement. Perte de connaissance prolongée. Aucun traitement administré.\n\nPREUVES — Spores identifiées au microscope, composés soporifiques dans le sang (GABA élevé), mélatonine induite, résidus polliniques documentés, tableau clinique cohérent (dépression respiratoire, myosis, hypotonie, bradycardie).\n⚖ Preuve médicale recevable auprès de la Ligue Pokémon."},
  {id:"005",ref:"REF/MED/2026-0515-YY",name:"Yummi Yamo",date:"15 / 05 / 2026",unit:"Consultation externe",status:"traite",category:"Toxicologie",tags:["Intoxication","Spores Raphlesia","Perte de connaissance"],summary:"Certificat attestant une intoxication involontaire par spores de Raphlesia. Aucun traitement administré.",body:"ATTESTATION — Intoxication par spores de Raphlesia subie sans consentement. Perte de connaissance prolongée. Aucun traitement administré.\n\nPREUVES — Spores identifiées au microscope, composés soporifiques dans le sang (GABA élevé), mélatonine induite, résidus polliniques documentés, tableau clinique cohérent.\n⚖ Preuve médicale recevable auprès de la Ligue Pokémon."},
  {id:"006",ref:"REF/MED/2026-0515-TD",name:"Tony Delord",date:"15 / 05 / 2026",unit:"Admission · Urgences chirurgicales",status:"traite",category:"Médecine légale",tags:["Pendaison forcée","Traumatisme cervical","Chute","Médico-légal"],summary:"Pendaison forcée suivie d'une chute. Bilan neurologique rassurant, réveil confirmé, sortie autorisée.",body:"⚠ SIGNALEMENT MÉDICO-LÉGAL — Pendaison forcée confirmée par marques de lutte. Photographies et prélèvements sous-unguéaux. Signalement aux autorités.\n\nADMISSION — Inconsciente, aucune marque de ligature, marques de lutte, intubation en urgence.\nINTERVENTIONS — Intubation, scanner cérébral/cervical (RAS), écho-doppler carotidien (RAS), bilan sanguin normal, cartographie des ecchymoses.\nTRAITEMENT — Corticoïdes IV, Mannitol, Morphine, Antibiotiques.\n✓ Réveil confirmé, aucune séquelle majeure, sortie autorisée. Plus de peur que de mal."},
  {id:"007",ref:"REF/MED/2026-0515-KU",name:"Kimaru Ukasai",date:"15 / 05 / 2026",unit:"Admission · Traumatologie",status:"traite",category:"Traumatologie",tags:["Traumatologie","Fracture","Chute 3-4m"],summary:"Fractures légères du col du fémur et du calcanéum après chute. Sortie avec béquille.",body:"ADMISSION — Chute de 3 à 4 m sur les membres inférieurs. Patient conscient.\nDIAGNOSTICS — Fracture légère du col du fémur. Fracture légère du calcanéum.\nTRAITEMENT — Radiographies, antalgie renforcée (euphorie favorisant la régénération), crème Baie Sitrus, béquille fournie.\n✓ Sortie autorisée, suivi en consultation externe."},
  {id:"001-OP",ref:"REF/MED/2026-0623-ZC",name:"Zerath Cobalt",date:"23 / 06 / 2026",unit:"Chirurgie programmée · Bloc opératoire",status:"traite",category:"Chirurgie",tags:["Chirurgie oculaire","Chirurgie prothétique","Orbite","Main"],summary:"Double intervention : préparation orbitaire définitive et pose de prothèse de main (pouce, index, paume). Aucune complication.",body:"CONTEXTE — Admis le 12/05, œil nécrosé retiré, implant provisoire. Opération en deux temps.\n\nPARTIE 1 — ORBITE : retrait du conformateur provisoire, régularisation conjonctivale, hémostase bipolaire, implant orbitaire poreux définitif, suture 6-0, conformateur acrylique, pommade Tobramycine.\n\nPARTIE 2 — PROTHÈSE DE MAIN : incision palmaire en L, plaque palmaire titane vissée, tendons ancrés, pouce et index prothétiques titane verrouillés, fermeture Histoacryl, crème Baie Sitrus.\n\n✓ Aucune complication. Suivi : œil de verre définitif en consultation externe."},
  {id:"008",ref:"REF/MED/2026-0623-LP",name:"Léo Poulino",date:"23 / 06 / 2026",unit:"Admission · Urgences chirurgicales",status:"traite",category:"Traumatologie",tags:["Traumatologie","Fractures costales","Fracture fémur","Chirurgie simultanée"],summary:"Trois côtes brisées et fémur cassé, opérés simultanément. Plaques costales et clou centromédullaire. Aucune complication.",body:"ADMISSION — Trois côtes brisées + fracture du fémur. Double intervention simultanée sous anesthésie générale.\n\nCÔTES — Incision latérale thoracique, fixation des trois côtes par plaques titane + vis 2mm, étanchéité pleurale confirmée, fermeture Histoacryl.\n\nFÉMUR — Incision latérale cuisse, réduction, clou centromédullaire titane verrouillé (proximal + distal), attelle plâtrée postérieure.\n\nTRAITEMENT — Antibiotiques IV, Morphine, Anticoagulants, Anti-inflammatoires, crème Baie Sitrus.\n✓ Aucune complication. Contrôle radiologique à 6 semaines."},
  {id:"ML-001",ref:"REF/MED/2026-0623-ML",name:"Balash Mové",date:"23 / 06 / 2026 · 18H36",unit:"Unité médico-légale · Autopsie",status:"deces",category:"Médecine légale",tags:["Décès","Traumatisme crânien","Autopsie"],summary:"Autopsie médico-légale. Décès par traumatisme crânien occipital. Toxicologie négative. Dossier clôturé.",body:"INFORMATIONS — Défunt : Balash Mové. Décès à 18H36 le 23/06/2026. Lieu et circonstances non communiqués.\n\nEXAMEN EXTERNE — Lividités et rigidité cohérentes. Aucune ligature/brûlure/piqûre. Plaie occipitale, hématome et enfoncement osseux.\n⚠ Enfoncement compatible avec impact de forte énergie sur surface réduite — origine à déterminer.\n\nEXAMEN INTERNE — Fracture occipitale étoilée, hématome extradural massif, engagement cérébral (cause du décès).\n\nTOXICOLOGIE — Sang, humeur vitrée, urine normaux. Alcool/drogues/médicaments négatifs. Panel venins Pokémon négatif.\n✓ Cause exclusivement traumatique. Absence de signes de lutte. Rapport transmis aux autorités."}
];

export default async () => {
  const existing = await store().get(KEY, { type: "json" });
  if (Array.isArray(existing) && existing.length > 0) {
    return new Response(
      JSON.stringify({ ok: true, seeded: false, message: "Registre déjà rempli, aucune modification.", count: existing.length }),
      { status: 200, headers: { "Content-Type": "application/json" } }
    );
  }
  const withDates = SEED.map((r) => ({ ...r, createdAt: new Date().toISOString() }));
  await store().setJSON(KEY, withDates);
  return new Response(
    JSON.stringify({ ok: true, seeded: true, count: withDates.length }),
    { status: 200, headers: { "Content-Type": "application/json" } }
  );
};

export const config = { path: "/api/seed" };
